#!/bin/bash

xgettext --language=Python --keyword=_ --output=mauna-common.pot usr/bin/* usr/lib/python3/dist-packages/maunacommon/*.py usr/lib/python3/dist-packages/maunacommon/installer/*.py usr/lib/mauna/common/*


